woowacourse-teams/2025-Turip

- .github/pull_request_template.md
- .github/workflows/review-assign.yml
- closed #16
- PR 오픈 시 `Reviewers` 및 `Assignees` 자동 등록되도록 CI 를 구축했습니다!
- 안드로이드 / 백엔드 경로에 따라 리뷰어 설정을 다르게 하도록 했습니다.
> [feat] PR 자동 리뷰어 등록 및 담당자 설정 CI 구축

- .github/workflows/android-ci.yml
- closed #14
안드로이드 CI 파이프라인 구축
- 빌드 자동화
- Ktlint 포맷팅 체크
- 테스트 자동화
- [GitHub Actions documentation](https://docs.github.com/en/actions)
> [feat] 안드로이드 CI 파이프라인 최초 구축

- .github/workflows/android-ci.yml
> [fix] 안드로이드 CI 수정

- backend/src/main/java/turip/TuripApplication.java
- closed #12 
- 프로젝트 명(focus with me -> turip) 변경으로 인한 패키지 명과 메인 애플리케이션 클래스 명 변경
> [feat] 프로젝트 디렉토리명 변경

- .github/workflows/android-ci.yml
- android/app/build.gradle.kts
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/on/turip/TuripApplication.kt
- android/app/src/main/java/com/on/turip/data/network/NetworkClient.kt
- android/gradle.properties
- android/gradle/libs.versions.toml
- closed #11
- `retrofit2`, `kotlinx.serialization`, `serialization.converter`, `okhttp`, `okhttp-logging-interceptor` 의존성을 추가했습니다.
- retrofit2: REST Api 를 위함
- kotlinx.serialization: JSON 직렬화
- serialization.converter: retrofit 에서 serialization 으로 컨버팅 시 사용
- okhttp 및 okhttp-logging-interceptor: 통신 시 로깅으로 디버깅 용이하게 (응답의 로그(헤더, 바디 등)를 출력해주는 인터셉터)
- 인터넷 권한 추가했습니다.
- `TuripApplication` 을 생성해서 앱 진입점으로 설정했습니다.
- 기본 `NetworkClient`을 세팅했습니다.
```
!!!!!! 중요 !!!!!! 노션 들어가서 `쉿!` 에 local.properties 업데이트하기
```
빌드 되는 거 확인함!
[Retrofit 문서](https://square.github.io/retrofit/contributing/)
[Kotlinx.serialization 문서](https://github.com/Kotlin/kotlinx.serialization)
[okhttp 문서](https://square.github.io/okhttp/)
[okhttp-logging-interceptor](https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor …
> [feat] network 세팅

- backend/src/main/java/turip/creator/controller/CreatorController.java
- backend/src/main/java/turip/creator/controller/dto/response/CreatorResponse.java
- backend/src/main/java/turip/creator/repository/CreatorRepository.java
- backend/src/main/java/turip/creator/service/CreatorService.java
- backend/src/main/java/turip/exception/NotFoundException.java
- closed #42 
- 크리에이터 조회 api 구현
- not found 커스텀 예외 구현
> [feat] Creator 조회 api 구현 

- backend/src/main/java/turip/creator/controller/CreatorController.java
- closed #45 
ResponseEntity를 통해 상태 코드를 표현하기 때문에 `@ResponseStatus`를 삭제
> [feat] ResponseStatus 애노테이션 제거

- backend/src/main/resources/application.yml
- closed #47 
애플리케이션 환경 설정 파일 추가
> [feat] application 환경 설정

- backend/build.gradle
- backend/src/main/java/turip/content/controller/ContentController.java
- backend/src/main/java/turip/content/controller/dto/response/ContentCountResponse.java
- backend/src/main/java/turip/content/repository/ContentRepository.java
- backend/src/main/java/turip/content/service/ContentService.java
- backend/src/test/java/turip/content/api/ContentApiTest.java
- closed #51 
지역별 컨텐츠 수 조회 api와 통합 테스트 추가했습니다. junit 의존성도 빠져있어서 추가해뒀어요!
> [feat] 지역별 컨텐츠 수 조회 api 구현

- .github/workflows/backend-dev-server.yml
- closed #75 
github actions를 이용해서 CI, CD 환경을 구축했습니다
> [feat] CI/CD 설정 추가

- backend/src/main/java/turip/content/controller/ContentController.java
- backend/src/main/java/turip/creator/controller/dto/response/CreatorResponse.java
- backend/src/test/java/turip/content/api/ContentPagingApiTest.java
- closed #84 
- 지역별 컨텐츠 목록 조회 api에서 받아올 컨텐츠의 크기 key값을 size, 마지막 컨텐츠 아이디 key값을 lastId로 수정
- 크리에이터 조회 api에서 프로필 이미지 대신 채널명 받아오는 오류 수정
> [fix] api 파라미터 Key값, 크리에이터 응답 형식 오류 수정

- backend/src/main/java/turip/tripcourse/domain/TripCourse.java
- backend/src/main/resources/application.yml
- backend/src/main/resources/data.sql
- backend/src/test/resources/application.yml
- closed #82 
부산 브이로그 2개에 대한 초기 데이터 추가하고, TripCourse와 Place에 대한 연관관계를 1:N으로 수정했습니다!
> [feat] 초기 데이터 추가

- backend/src/main/resources/application.yml
- backend/src/main/resources/data.sql
- backend/src/main/resources/hachantour_gangwon_data.sql
- backend/src/main/resources/jejueddy_gangwon_sokcho_data.sql
- backend/src/main/resources/jejueddy_posak_date.sql
- backend/src/main/resources/yeoconam_gangwon_gyeongju_data.sql
- backend/src/main/resources/yeoconam_ganwon_gangneung_data.sql
- backend/src/main/resources/yeoconam_seoul_data.sql
- closed #이슈번호
초기 데이터 6개 추가했습니다.
> feat: 데이터 추가

- backend/src/main/resources/yeoconam_gangwon_gyeongju_data.sql
- backend/src/main/resources/yeoconam_ganwon_gangneung_data.sql
> [feat] 데이터 수정

- backend/src/main/java/turip/content/controller/ContentController.java
> [fix] 충돌해결

- backend/src/main/java/turip/content/controller/ContentController.java
- backend/src/test/java/turip/content/api/ContentApiTest.java
- closed #158 
검색 관련 api의 엔드포인트를 수정했습니다!
> [refactor] 검색 api 엔드포인트 수정

- backend/src/main/java/turip/log/LoggingInterceptor.java
- backend/src/main/resources/logback-spring.xml
- closed #142 
- 로그에 추가적으로 있을 것 같은 내용 추가했습니다
- 요청 사용자 정보 => remoteAddr(ip 주소), userAgent(사용자의 OS, 브라우저, 기기 정보)
- 예외 stack trace
- timestamp는 Asia/Seoul 기준으로 수정
> [feat] 로깅 프레임워크 적용 및 로그 관련 코드 추가 

- android/app/src/main/java/com/on/turip/ui/common/ItemDividerDecoration.kt
- android/app/src/main/java/com/on/turip/ui/main/favorite/FavoriteFragment.kt
- android/app/src/main/java/com/on/turip/ui/main/favorite/FavoriteItemAdapter.kt
- android/app/src/main/java/com/on/turip/ui/main/favorite/FavoriteItemViewHolder.kt
- android/app/src/main/java/com/on/turip/ui/main/favorite/FavoriteViewModel.kt
- android/app/src/main/res/layout/fragment_favorite.xml
- android/app/src/main/res/layout/item_favorite.xml
- closed #148
- 찜 목록 페이지 UI 구현
https://github.com/user-attachments/assets/716173a2-642f-4351-ac48-b97f2bb3cc9f
> [feat] 찜 목록 UI 구현

- backend/src/main/java/turip/regioncategory/service/RegionCategoryService.java
- backend/src/main/resources/Region/region_data.sql
- closed #185 
빠른 이미지 로드를 위해 사진을 변환하고, Image url을 수정했습니다!
> [refactor] 지역 이미지 경로 변경

- android/app/src/main/java/com/on/turip/ui/trip/detail/PlaceModel.kt
- android/app/src/main/java/com/on/turip/ui/trip/detail/TripPlaceViewHolder.kt
- android/app/src/main/res/layout/activity_trip_detail.xml
- closed #186 
- 카테고리가 깊어지는 경우에도 파악하기 쉽도록 수정하였습니다.
- 수정 전 -> 수정 후
> [feat] 영상 상세 페이지 QA 진행 후 반영사항

- android/app/src/main/java/com/on/turip/ui/common/TuripUrlConverter.kt
- android/app/src/main/java/com/on/turip/ui/search/keywordresult/SearchActivity.kt
- android/app/src/main/res/layout/activity_search.xml
- android/app/src/main/res/values/strings.xml
- android/app/src/test/java/com/on/turip/ui/common/TuripUrlConverterTest.kt
- closed #184
- 검색창에 있는 검색바의 전체 삭제 버튼 영역 키우기
- 검색창 공백일 때 검색되지 않도록 수정
- 예시 검색어 ux라이팅을 검색 가능한 검색어로 바꾸기(1박 2일, 느좋>> 안 나옴)
- 검색바 전체 클릭되도록 수정
[Screen_recording_20250807_221608.webm](https://github.com/user-attachments/assets/b05ba20b-33e9-4280-bcf7-b611e72bb322)
> [feat] 검색 화면 3차 데모데이 QA

- backend/build.gradle
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-prod.yml
- backend/src/main/resources/application.yml
- closed #206 
`application-dev.yml`, `application-prod.yml` 분리했습니다! db 만들고 application-prod.yml에 설정 추가해주면 됩니당
> [feat] 운영 환경 분리

- android/app/src/main/res/values/strings.xml
> [feat] 유저들이 많이 찜한 콘텐츠 타이틀 ux 수정

- backend/src/main/java/turip/configuration/DevWebMvcConfiguration.java
- backend/src/main/java/turip/exception/GlobalExceptionHandler.java
- backend/src/main/java/turip/log/LoggingFilter.java
- backend/src/main/java/turip/log/LoggingInterceptor.java
- backend/src/main/resources/logback-spring.xml
> [feat] 로깅 전략 개선

- android/app/src/main/java/com/on/turip/data/folder/FolderMapper.kt
- android/app/src/main/java/com/on/turip/data/folder/datasource/DefaultFolderRemoteDataSource.kt
- android/app/src/main/java/com/on/turip/data/folder/datasource/FolderRemoteDataSource.kt
- android/app/src/main/java/com/on/turip/data/folder/dto/FavoriteFolderAddRequest.kt
- android/app/src/main/java/com/on/turip/data/folder/repository/DefaultFolderRepository.kt
- android/app/src/main/java/com/on/turip/data/folder/service/FolderService.kt
- android/app/src/main/java/com/on/turip/domain/folder/repository/FolderRepository.kt
- android/app/src/main/java/com/on/turip/ui/folder/FolderAddBottomSheetFragment.kt
- android/app/src/main/java/com/on/turip/ui/folder/FolderAddBottomSheetViewModel.kt
- closed #270
- 장소 찜 폴더 생성 API를 연결했습니다.
[record.webm](https://github.com/user-attachments/assets/536d047b-75d2-41a8-8068-639952bf4818)
> [feat] 장소 찜 폴더 생성 API 연결

- android/app/src/main/java/com/on/turip/ui/trip/detail/TripDetailActivity.kt
- android/app/src/main/res/layout/fragment_favorite_place.xml
- android/app/src/main/res/layout/item_place_folder_name.xml
> [feat] 5차 QA (제리 담당)

- README.md
- closed #368
- 리드미 업데이트 했습니다!
https://github.com/woowacourse-teams/2025-Turip/tree/feature/%23368 여기서 확인해보세욧
> [feat] 리드미 업데이트
